# .github/workflows/draft-release.yml
# 🔄 Automatischer Draft-Release-Workflow nach Merge auf main

name: Create Draft Release

on:
  workflow_dispatch:

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
