name: On GitHub Release

on:
  release:
    types: [published]

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract release version from tag
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update version.txt
        run: echo "$RELEASE_VERSION" > version.txt

      - name: Commit version.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Update version.txt to $RELEASE_VERSION"
          git push
